[1] Connecting to "Smart Lock [Group 3]"...
[Mutation] Appended extra byte: 69
[Mutation Auth 0] Sending AUTH command with mutated passcode: [1, 2, 3, 4, 5, 6, 69]
[Mutation Auth 0] Authentication failed with mutated passcode.
[Mutation] Appended extra byte: 235
[Mutation Auth 1] Sending AUTH command with mutated passcode: [1, 2, 3, 4, 5, 6, 235]
[Mutation Auth 1] Error sending AUTH command: [WinError -2147023673] The operation was canceled by the user
An OSError occurred, reconnecting to device
[Mutation] Appended extra byte: 187
[Mutation Auth 2] Sending AUTH command with mutated passcode: [1, 2, 3, 4, 5, 6, 187]
[Mutation Auth 2] Authentication failed with mutated passcode.
[Mutation] Appended extra byte: 238
[Mutation Auth 3] Sending AUTH command with mutated passcode: [1, 2, 3, 4, 5, 6, 238]
[Mutation Auth 3] Error sending AUTH command: [WinError -2147023673] The operation was canceled by the user
An OSError occurred, reconnecting to device
[Mutation] Appended extra byte: 181
[Mutation Auth 4] Sending AUTH command with mutated passcode: [1, 2, 3, 4, 5, 6, 181]
[Mutation Auth 4] Authentication failed with mutated passcode.
[X] Mutation-based authentication did not succeed after several attempts. Exiting.
Task was destroyed but it is pending!
task: <Task cancelling name='Task-2' coro=<BLEClient._serialport_task() running at C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\BLEClient.py:92> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\asyncio\tasks.py:767]>
