
==================================================
[+] Starting new fuzzing cycle
==================================================
[1] Connecting to "Smart Lock [Group 3]"...
[Mutation] Byte 0: 1 -> 0, Byte 1: 2 -> 194, Byte 2: 3 -> 2, Byte 3: 4 -> 28, Byte 4: 5 -> 133, Byte 5: 6 -> 42

[Random Auth 0] Trying: [0, 194, 2, 28, 133, 42]
[!] Command: [0, 0, 194, 2, 28, 133, 42]
[!] Response: 1
[!] Authentication failed
[Mutation] Byte 0: 1 -> 117

[Random Auth 1] Trying: [117, 2, 3, 4, 5, 6]
[!] Command: [0, 117, 2, 3, 4, 5, 6]
[!] Response: 1
[!] Authentication failed
[Mutation] Byte 2: 3 -> 39

[Random Auth 2] Trying: [1, 2, 39, 4, 5, 6]
[!] Command: [0, 1, 2, 39, 4, 5, 6]
[!] Response: 1
[!] Authentication failed

[Random Auth 3] Trying: [156, 49, 163, 38, 140, 28]
[!] Command: [0, 156, 49, 163, 38, 140, 28]
[!] Response: 1
[!] Authentication failed

[Random Auth 4] Trying: [163, 53, 120, 36, 130, 21]
[!] Command: [0, 163, 53, 120, 36, 130, 21]
[!] Response: 1
[!] Authentication failed

[Random Auth 5] Trying: [188, 82, 173, 204, 21, 122]
[!] Command: [0, 188, 82, 173, 204, 21, 122]
[!] Response: 1
[!] Authentication failed
[Mutation] Byte 3: 4 -> 60

[Random Auth 6] Trying: [117, 2, 3, 60, 5, 6]
[!] Command: [0, 117, 2, 3, 60, 5, 6]
[!] Response: 1
[!] Authentication failed

[Random Auth 7] Trying: [121, 165, 164, 220, 212, 217]
[!] Command: [0, 121, 165, 164, 220, 212, 217]
[!] Response: 1
[!] Authentication failed
[Mutation] Byte 0: 0 -> 21, Byte 1: 194 -> 130, Byte 2: 2 -> 50, Byte 3: 28 -> 84, Byte 4: 133 -> 165, Byte 5: 42 -> 238

[Random Auth 8] Trying: [21, 130, 50, 84, 165, 238]
[!] Command: [0, 21, 130, 50, 84, 165, 238]
[!] Response: 1
[!] Authentication failed
[Mutation] Changed length from 6 to 7 bytes

[Random Auth 9] Trying: [121, 165, 164, 220, 212, 217, 48]
[!] Command: [0, 121, 165, 164, 220, 212, 217, 48]
[!] Response: 1
[!] Authentication failed
[!] Authentication fuzzing failed, trying with correct passcode...
[+] Authenticated with correct passcode
[Mutation] Byte 0: 2 -> 116

[Random Command 0] Sending: [116]
[!] Command: [116]
[!] Response: 2

[Random Command 1] Sending: [1, 141, 40]
[!] Command: [1, 141, 40]
[!] Response: 0

[Random Command 2] Sending: [2, 190, 147, 224, 158]
[!] Command: [2, 190, 147, 224, 158]
[!] Response: 0
[Mutation] Byte 0: 116 -> 115

[Random Command 3] Sending: [115]
[!] Command: [115]
[!] Response: 2
[Mutation] Byte 0: 2 -> 55

[Random Command 4] Sending: [55]
[!] Command: [55]
[!] Response: 2

[Random Command 5] Sending: [1, 206, 211, 237]
[!] Command: [1, 206, 211, 237]
[!] Response: 0

[Random Command 6] Sending: [2, 37, 234, 23, 152]
[!] Command: [2, 37, 234, 23, 152]
[!] Response: 0
[Mutation] Byte 0: 115 -> 75

[Random Command 7] Sending: [75]
[!] Command: [75]
[!] Response: 2
[Mutation] Changed length from 1 to 2 bytes

[Random Command 8] Sending: [2, 124]
[!] Command: [2, 124]
[!] Response: 4

[Random Command 9] Sending: [115]
[!] Command: [115]
[!] Response: 2

[Disconnecting...]

[Logs from Smart Lock (Serial Port)]:
--------------------------------------------------

[Bluetooth] User Connected
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[AUTH] Authentication Failed
[Bluetooth] Received command: 0x00 (Authenticate)
[Auth] Authentication Sucessfull
[State] Device state: Authenticated
[Bluetooth] Received command: 0x01 (Open)
[Bluetooth] Received command: 0x02 (Close)
[Bluetooth] Received command: 0x01 (Open)
[Bluetooth] Received command: 0x02 (Close)
[Bluetooth] Received command: 0x02 (Close)
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-2' coro=<BLEClient._serialport_task() done, defined at C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\BLEClient.py:72> exception=SerialException("could not open port 'COM6': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)")>
Traceback (most recent call last):
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\BLEClient.py", line 79, in _serialport_task
    line = await run.io_bound(port.readline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\nicegui\run.py", line 74, in io_bound
    return await _run(thread_pool, callback, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\nicegui\run.py", line 52, in _run
    return await loop.run_in_executor(executor, partial(callback, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\serial\serialwin32.py", line 275, in read
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\BLEClient.py", line 91, in _serialport_task
    port = self.open_serialport()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\BLEClient.py", line 55, in open_serialport
    self.serialport = serial.Serial(
                      ^^^^^^^^^^^^^^
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\SUTD\TERM_6\STV\smart-lock-ctf-2025\venv\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM6': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
